### ISSUE TITLE
Feature Request : Detecting Architecture Smells for Java projects?

### ISSUE THREAD

**Issue by yottabytt** [tushartushar/DesigniteJava#68]
Can you please build something like [this](http://www.designite-tools.com/designite/does-your-architecture-smell/ ) for Java projects too.

**Comment by tushartushar** [comment]
Yes, it is on the radar. Stay tuned.

**Comment by tushartushar** [comment]
Its done. Check the [Enterprise](https://www.designite-tools.com/designitejava/) edition of DesigniteJava.
