### ISSUE TITLE
Cannot mvn clean install due to test failures

### ISSUE THREAD

**Issue by JMcDonald1999** [tushartushar/DesigniteJava#78]
Tests run: 135, Failures: 3, Errors: 57, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.638 s
[INFO] Finished at: 2022-01-05T21:46:55Z
[INFO] ------------------------------------------------------------------------

Any solutions for this?
Tests seem to fail when run locally as well, appears to be a mockito issue

**Comment by NikolasPpd** [comment]
I get the same exact problem. Did you find any solution?

**Comment by gustavopintozup** [comment]
Same here, but you can still built the jar skipping the tests (` -Dmaven.test.skip`)

**Comment by tushartushar** [comment]
The build is passing now.
