### ISSUE TITLE
Metric for some code smells

### ISSUE THREAD

**Issue by sac111** [tushartushar/DesigniteJava#79]
What metrics along with their threshold value have been used to detect below code smells in the tool?
1.Magic number
2. Feature envy
3. Complex condition
4. Empty catch block

Kindly provide the response as I could not find it.

**Comment by tushartushar** [comment]
A note: not every smells can be detected using metrics; some smells uses heuristics/rules (sometimes combined with metrics)

> 1. Magic number

Any number in code except `0` and `1` is a magic number
> 2. Feature envy

`method calls and field accesses to its present class` < `method calls and field accesses to another class`
> 3. Complex condition

Three or more conditions in a conditional (eg `if` statement) block
> 4. Empty catch block

`No of statements in the catch block` = 0

**Comment by sac111** [comment]
Thanks a lot. It means we can not detect these code smells using the datasets while using a machine learning technique.
